sudo: required

language: python

python:
  - "3.5"

branches:
  only:
    - master

env:
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='lms+discovery+forum'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='lms+marketing'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='lms+registrar'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='ecommerce'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='edx_notes_api'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='credentials'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 SERVICES='analyticspipeline'

services:
  - docker

before_install:
  # Upgrade Docker to the latest version
  - docker version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - docker-compose --version
  - make requirements
  - make dev.clone
  - make dev.pull."$SERVICES"

script:
  - make dev.provision."$SERVICES"
  - make dev.up."$SERVICES"
  - make dev.check."$SERVICES"
